# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: classifier 1.3.5 ruby lib

Gem::Specification.new do |s|
  s.name = "classifier"
  s.version = "1.3.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.autorequire = "classifier"
  s.date = "2015-07-30"
  s.email = "lucas@rufy.com"
  s.executables = ["bayes.rb", "summarize.rb"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.markdown"
  ]
  s.files = [
    ".travis.yml",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.markdown",
    "Rakefile",
    "VERSION",
    "bin/bayes.rb",
    "bin/summarize.rb",
    "classifier.gemspec",
    "install.rb",
    "lib/classifier.rb",
    "lib/classifier/bayes.rb",
    "lib/classifier/extensions/string.rb",
    "lib/classifier/extensions/vector.rb",
    "lib/classifier/extensions/vector_serialize.rb",
    "lib/classifier/extensions/word_hash.rb",
    "lib/classifier/lsi.rb",
    "lib/classifier/lsi/content_node.rb",
    "lib/classifier/lsi/summary.rb",
    "lib/classifier/lsi/word_list.rb",
    "test/bayes/bayesian_test.rb",
    "test/extensions/word_hash_test.rb",
    "test/lsi/lsi_test.rb",
    "test/test_helper.rb"
  ]
  s.homepage = "https://github.com/cardmagic/classifier"
  s.rubygems_version = "2.4.5"
  s.summary = "Ruby Classifier - Bayesian and LSI classification library"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rake>, [">= 0"])
      s.add_runtime_dependency(%q<rspec>, [">= 0"])
      s.add_runtime_dependency(%q<rdoc>, [">= 0"])
      s.add_runtime_dependency(%q<ruby-stemmer>, [">= 0"])
      s.add_runtime_dependency(%q<fast-stemmer>, [">= 1.0.0"])
    else
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<rdoc>, [">= 0"])
      s.add_dependency(%q<ruby-stemmer>, [">= 0"])
      s.add_dependency(%q<fast-stemmer>, [">= 1.0.0"])
    end
  else
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<rdoc>, [">= 0"])
    s.add_dependency(%q<ruby-stemmer>, [">= 0"])
    s.add_dependency(%q<fast-stemmer>, [">= 1.0.0"])
  end
end

